/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "bank.h"
#include<stdio.h>


void
bank_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	usr_pass  init_1_arg;
	double  *result_2;
	usr_pass  verify_1_arg;
	double  *result_3;
	double  balance_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, BANK, SWISS_BANK, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	
	strcpy(init_1_arg.usr,"les");
	strcpy(init_1_arg.pass,"lamport");
	
	result_1 = init_1(&init_1_arg, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	strcpy(verify_1_arg.usr,"les");
	strcpy(verify_1_arg.pass,"lamport");
	
	
	
	result_2 = verify_1(&verify_1_arg, clnt);
	if (result_2 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	
	if(*result_2 == 0.0)
		exit(0);
		
		
	balance_1_arg = 3000.0;
		
	result_3 = balance_1(&balance_1_arg, clnt);
	if (result_3 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	if(*result_3 == 1){
	
		printf("\ntransaction complete...");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	bank_1 (host);
exit (0);
}
