/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "bank.h"

bool_t
xdr_usr_pass (XDR *xdrs, usr_pass *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->usr, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->pass, 100,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
