/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AVG_H_RPCGEN
#define _AVG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct numbers {
	double nos[200];
	int vals;
};
typedef struct numbers numbers;

#define AVERAGE 35000
#define AVG 1

#if defined(__STDC__) || defined(__cplusplus)
#define cal_avg 1
extern  double * cal_avg_1(numbers *, CLIENT *);
extern  double * cal_avg_1_svc(numbers *, struct svc_req *);
extern int average_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define cal_avg 1
extern  double * cal_avg_1();
extern  double * cal_avg_1_svc();
extern int average_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_numbers (XDR *, numbers*);

#else /* K&R C */
extern bool_t xdr_numbers ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AVG_H_RPCGEN */
