/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "avg.h"

bool_t
xdr_numbers (XDR *xdrs, numbers *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->nos, 200,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->vals))
		 return FALSE;
	return TRUE;
}
