/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _REV_H_RPCGEN
#define _REV_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct strg {
	char s[30];
};
typedef struct strg strg;

#define REVERSE 9000
#define REV 1

#if defined(__STDC__) || defined(__cplusplus)
#define str_rev 1
extern  strg * str_rev_1(char **, CLIENT *);
extern  strg * str_rev_1_svc(char **, struct svc_req *);
extern int reverse_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define str_rev 1
extern  strg * str_rev_1();
extern  strg * str_rev_1_svc();
extern int reverse_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_strg (XDR *, strg*);

#else /* K&R C */
extern bool_t xdr_strg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_REV_H_RPCGEN */
