/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_H_RPCGEN
#define _FILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SUBSTRING 444
#define SUB 1

#if defined(__STDC__) || defined(__cplusplus)
#define sub 1
extern  double * sub_1(char **, CLIENT *);
extern  double * sub_1_svc(char **, struct svc_req *);
extern int substring_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sub 1
extern  double * sub_1();
extern  double * sub_1_svc();
extern int substring_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_H_RPCGEN */
