/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "file.h"


void
substring_1(char *host, char * str)
{
	CLIENT *clnt;
	double  *result_1;
	//char * sub_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUBSTRING, SUB, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	
	
	result_1 = sub_1(&str, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("number of occurences: %e",*result_1);
	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *str;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	
	substring_1 (host, argv[2]);
exit (0);
}
