/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _USERS_H_RPCGEN
#define _USERS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct users {
	char user[400];
	char logins[400];
	int total;
};
typedef struct users users;

#define USERS 555
#define USE 1

#if defined(__STDC__) || defined(__cplusplus)
#define info 1
extern  users * info_1(double *, CLIENT *);
extern  users * info_1_svc(double *, struct svc_req *);
extern int users_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define info 1
extern  users * info_1();
extern  users * info_1_svc();
extern int users_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_users (XDR *, users*);

#else /* K&R C */
extern bool_t xdr_users ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_USERS_H_RPCGEN */
