/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "users.h"


void
users_1(char *host)
{
	CLIENT *clnt;
	users  *result_1;
	double  info_1_arg;
	int	i, k,j;
	
#ifndef	DEBUG
	clnt = clnt_create (host, USERS, USE, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = info_1(&info_1_arg, clnt);
	if (result_1 == (users *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	
//printf("%s\n%s\n", result_1->user, result_1->logins);
	
	k = 0;
	j = 0;
	
	printf("\nUser\t\tLogin@\n");
	
	for(i = 0 ; i< result_1->total ;i++){
	
		printf("\n");
		
		while(result_1->user[k]!=',' && result_1->user[k] !=0){
		
			printf("%c",result_1->user[k]);
			k++;
		
		}
		k++;
		printf("\t\t");
		while(result_1->logins[j]!=',' && result_1->logins[j] !=0){
		
			printf("%c",result_1->logins[j]);
			j++;
		
		}
		j++;
		
		printf("\n");
	
	}
	
	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	users_1 (host);
exit (0);
}
