/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "users.h"

bool_t
xdr_users (XDR *xdrs, users *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->user, 400,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->logins, 400,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->total))
		 return FALSE;
	return TRUE;
}
