/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ps.h"


void
remoteprocs_1(char *host)
{
	CLIENT *clnt;
	processes  *result_1;
	double  remotep_1_arg;
	int	i, j;
	
	remotep_1_arg = 9;


#ifndef	DEBUG
	clnt = clnt_create (host, REMOTEPROCS, PROCS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = remotep_1(&remotep_1_arg, clnt);
	if (result_1 == (processes *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	printf("\nProcesses on remote machine\n\nPID\t\tCMD");
	
	j = 1; 
	for(i = 0;i<= result_1->total;i++)
	{
	
		printf("\n%d\t\t", result_1->pid[i]);
		
		while( result_1->proc[j]!=',' && result_1->proc[j]!= 0 ){
	
			printf("%c",result_1->proc[j]);
			j++;
		}
		printf("\n");
		j++;
	
	}
	
	
	
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	remoteprocs_1 (host);
exit (0);
}
