/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ps.h"

processes *
remotep_1_svc(double *argp, struct svc_req *rqstp)
{
	static processes  result;
	FILE*	fp;
	char	line[80];
	int	pid;
	char	str[60][4];
	int	index = 0; 
	char	comma[2]=",";
	
	system("ps > ps.txt");
	
	fp = fopen("ps.txt","r");
	
	fgets(line, 80, fp);
	
	//strcpy(result.proc, line);
	
	while(1){
	
		if(fgets(line, 80, fp)== NULL)
		{
			break;
		}
	
		sscanf(line,"%d %s %s %s",&pid, str[0],str[1],str[2]);
	
		result.pid[index] = pid;
		strcat(result.proc, comma);
		strcat(result.proc, str[2]);
		index++;	
	
	}
	
	result.total = index - 1;

	return &result;
}
