/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PROCESS_H_RPCGEN
#define _PROCESS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXL 100

typedef char *str;

struct proc {
	str processes[10];
	int no;
	int proc_id[10];
};
typedef struct proc proc;

#define PROCESS 45000
#define PROC 1

#if defined(__STDC__) || defined(__cplusplus)
#define remote_procs 1
extern  proc * remote_procs_1(int *, CLIENT *);
extern  proc * remote_procs_1_svc(int *, struct svc_req *);
extern int process_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define remote_procs 1
extern  proc * remote_procs_1();
extern  proc * remote_procs_1_svc();
extern int process_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_str (XDR *, str*);
extern  bool_t xdr_proc (XDR *, proc*);

#else /* K&R C */
extern bool_t xdr_str ();
extern bool_t xdr_proc ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PROCESS_H_RPCGEN */
