/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "process.h"

bool_t
xdr_str (XDR *xdrs, str *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXL))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_proc (XDR *xdrs, proc *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->processes, 10,
			sizeof (str), (xdrproc_t) xdr_str))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (1 +  10 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->no))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->proc_id, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->no);
			{
				register int *genp;

				for (i = 0, genp = objp->proc_id;
					i < 10; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->processes, 10,
			sizeof (str), (xdrproc_t) xdr_str))
			 return FALSE;
		buf = XDR_INLINE (xdrs, (1 +  10 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->no))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->proc_id, 10,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->no = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->proc_id;
					i < 10; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->processes, 10,
		sizeof (str), (xdrproc_t) xdr_str))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->no))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->proc_id, 10,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}
