/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SEARCH_H_RPCGEN
#define _SEARCH_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define SEARCH 877
#define S 1

#if defined(__STDC__) || defined(__cplusplus)
#define searchx 1
extern  double * searchx_1(char **, CLIENT *);
extern  double * searchx_1_svc(char **, struct svc_req *);
extern int search_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define searchx 1
extern  double * searchx_1();
extern  double * searchx_1_svc();
extern int search_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SEARCH_H_RPCGEN */
